name: CI

on: [push, pull_request]

env:
  IMAGE_NAME: hrituja/python-pytest
  IMAGE_TAG: v1

env:
  IMAGE_NAME: hrituja/python-pytest
  IMAGE_TAG: v1


jobs:
  common-ci:
    uses: HritzWalunj/common-ci-infra/.github/workflows/common-ci-pipeline.yml@main
    with:
      target_paths: |
        calculator
        tests

  build_docker_image:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.demo
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

  test:
    name: Unit Tests (inside Docker image)
    runs-on: ubuntu-latest
    needs: build_docker_image

    container:
      image: hrituja/python-pytest:v1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run pytest
        run: pytest

